### ISSUE TITLE
No Virtual Aladdin Connect Device Available to choose

### ISSUE THREAD

**Issue by mdmasterson** [tomwpublic/hubitat_aladdinConnect#14]
I have a Genie Aladdin Connect enabled garage door opener and would like to interface this with my Hubitat C-7 hub.  I have read the readme file and installed the two supplied drivers on my hub.  I see both drivers listed under my drivers code page.  However, when I attempt to install the device, I cannot find the choice suggested in the readme file.  I go to Devices>Add Device>Virtual>Type*> and under the Subset Virtual there is a Virtual Garage Door Controller but none listed as Aladdin Connect System.  If I scroll further down the Virtual device list I see the Subset "System" but again no Aladdin Connect choice.  I have rebooted the hub following the Driver install but no devices matching the description appear.  Can you assist?

**Comment by tomwpublic** [comment]
There's a separate section for custom drivers like this one. You may have to scroll even farther beyond the initial alphabetical list of system devices to see it. Also, you can just start typing the name "Aladdin" and it should filter the list to make it easier to find.

**Comment by mdmasterson** [comment]
Great. It appeared with the search. Thanks for the help.

**Comment by mdmasterson** [comment]
One last question hopefully. The controller appeared and works well to open
and close the door but it is listed with a battery that is at 0 percent
charge on my battery monitor. Is there a way to remove the fictional
battery?

**Comment by tomwpublic** [comment]
Unfortunately their API reports the battery life, even if there isn't one present. Since it's not possible to tell the difference between a dead battery and a non-existent one, I err on the side of caution and always report it.

You could comment out or remove the line that says `capability "Battery"` in the driver source file to see if that makes it go away in your battery monitor app.
