### ISSUE TITLE
Hubitat Aladdin Connect Homekit integration

### ISSUE THREAD

**Issue by finepl** [tomwpublic/hubitat_aladdinConnect#17]
Is it possible to add Aladin Connect to Homekit like the rest of my locks and switches?

**Comment by tomwpublic** [comment]
Did you try it?

**Comment by finepl** [comment]
I enabled the Homekit setting in the parent and 3 child devices.  However, none of these show up in the Hubitat Homekit Integration app.I have tried setting ‘Status Attribute’ to None, Door, Battery and RSSI.  All three attributes are appropriate for each door.  Perhaps you need to set an attribute type that is supported by the Hubitat Homekit Integration app.  However, the devices perform properly within the Hubitat.  The center door reports ‘UL Lockout’ because of a faulty position sensor.  I have the same issue within the Aladdin App.My existing Z-Wave switches and Yale lock are properly showing in Homekit.See attached documents for screenshots.Peter Fine224 North StreetRidgefield, CT ***@***.*** Dec 22, 2023, at 11:17 AM, tomwpublic ***@***.***> wrote:﻿
Did you try it?

**Comment by benfeely** [comment]
Thank you for the work to create these drivers!

I have the same question.  I have enabled Homekit option for the child device (Garage Door) and am unable to see the device in the list of devices in the Hubitat Homekit Integration view.  I also restarted the integration and no change.

**Comment by benfeely** [comment]
I just discovered that the garage door IS listed in the settings for the Homekit integration in the "authorizedDevices" list.  However, it does not show in the main integration view as a configurable device.

**Comment by benfeely** [comment]
I modified the metadata in the 'aladdinConnectGarageDoor' driver as shown below.  Given that this was a blind uninformed guess, I have not submitted a pull request directly.  Please let me know if this appears to be a valid fix and I will submit a PR. 

This appears to have resolved the issue for me.  The accessory now shows up as expected and behaves properly within the Apple Home app experience. 

`
metadata
{
    definition(name: "Aladdin Connect Garage Door", namespace: "tomw", author: "tomw", importUrl: "")
    {
        capability "Actuator"
        capability "Battery"
        capability "Garage Door Control"
        capability "Contact Sensor"
        capability "Signal Strength"
    }
}
`
