### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by mike-s123** [tomwpublic/hubitat_aladdinConnect#18]
FYI, Overhead Door has again made a breaking change to their API. If a user upgrades their phone app, it will move their account to the new API, and existing apps (including your driver) will no longer work properly. Open/Close still seems to work (at least right now), but status updates don't.

**Comment by valorp** [comment]
FYI, the folks running the HomeBridge plugin for Genie Aladdin plugin have addressed/fixed the latest breaking change in the API. 

I haven’t looked to see what it would take to update this package, but it should be relatively straightforward. 

https://github.com/derek-miller/homebridge-genie-aladdin-connect#readme

**Comment by tomwpublic** [comment]
I'm going to consider this integration deprecated and won't be providing any more updates.
