### ISSUE TITLE
refresh interval

### ISSUE THREAD

**Issue by joeroback** [tomwpublic/hubitat_aladdinConnect#7]
the refresh interval in minutes, set to minimum of 1

1.  does not ever allow for "opening" trigger to be seen really or consistently
2. 1 minute also is not useful for things like turn on switch/dimmer since i could easily miss the interval, open door, get out of car and be inside the house before the change is seen

can we consider changing the refresh to seconds instead of minutes?

**Comment by tomwpublic** [comment]
That is a valid suggestion that wouldn't be too hard to implement.

However, I was under the impression that this integration is broken due to the issues described here: https://community.hubitat.com/t/aladdin-connect-garage-door-driver/85995

So I was planning to hold off on making any changes until someone finds a workaround for that breakage that I can incorporate. But is yours still up and running?

**Comment by SamB1952** [comment]
Aside from the expected cloud delays, mine is working fine.  Just tested it.  Both the Aladdin Connect app and Hubitat are working.

**Comment by craigspree** [comment]
Can confirm still working for me as well

**Comment by joeroback** [comment]
yea, 100% working for me, i have installed via Hubitat package manager, running the latest hubitat firmware

**Comment by joeroback** [comment]
tho according to this https://github.com/home-assistant/core/issues/58946#issuecomment-1000377725 it appears aladdin is rolling out these changes and quite possible my account is still using the older API and they are moving to AWS and OAUTH..

i agree i'd hold off on any changes to see what comes out of this. my workaround is to just edit the driver code after install and hardcode the refresh timeout to 5s for now.

**Comment by tomwpublic** [comment]
I added an additional config option to use the refreshInterval inputs as seconds instead of minutes.  The default setting is still for minutes to preserve compatibility.  Version 1.1.2.  Hopefully it keeps working for you all for a while longer.

Change is here: #8
